name: Validate

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest
    name: Validate
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install homeassistant
          pip install voluptuous

      - name: Validate manifest
        run: |
          python -c "import json; json.load(open('custom_components/local_on_the_10s/manifest.json'))"

      - name: Validate translations
        run: |
          python -c "import json; json.load(open('custom_components/local_on_the_10s/translations/en.json'))"

      - name: Check Python syntax
        run: |
          python -m py_compile custom_components/local_on_the_10s/__init__.py
          python -m py_compile custom_components/local_on_the_10s/config_flow.py
          python -m py_compile custom_components/local_on_the_10s/const.py

      - name: Validate HTML
        run: |
          # Check that index.html exists and has basic structure
          grep -q "<!DOCTYPE html>" custom_components/local_on_the_10s/www/index.html
          grep -q "</html>" custom_components/local_on_the_10s/www/index.html

  hassfest:
    runs-on: ubuntu-latest
    name: Hassfest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run hassfest
        uses: home-assistant/actions/hassfest@master
